#!/bin/sh

# Prints the current volume or 🔇 if muted.

vol="$(amixer get 'PGA1.0 1 Master' | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"

# If muted, print 🔇 and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && echo 🔇 && exit

vol="${vol#Volume: }"

split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

case 1 in
	$((vol >= 60)) ) icon="🔊" ;;
	$((vol >= 1)) ) icon=" " ;;
	$((vol = 0)) ) icon="" ;;
	* ) echo  && exit ;;
esac

echo "$icon$vol%"
